### ISSUE TITLE
Can't use traefik for ingress

### ISSUE THREAD

**Issue by kalaytan** [jjcollinge/pgadmin-chart#7]
This is my generated template from airflow helm.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    component: web
    heritage: "Tiller"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/redirect-regex: "https?://([a-z0-9-_]+)*(?:[.]local[.]com|)/(.*)"
    traefik.ingress.kubernetes.io/redirect-replacement: "https://$1.local.com/$2"
spec:
  rules:
    - http:
        paths:
          - path: 
            backend:
              serviceName: pgadmin
              servicePort: web
      host: pgadmin.local.com
```
